quarkus.banner.enabled=false
quarkus.camunda.health.enabled=true
quarkus.http.test-port=0

#TODO: enable container image build again. Now disabled because of https://github.com/quarkiverse/quarkus-zeebe/issues/412
quarkus.container-image.build=false
quarkus.container-image.tag=latest
quarkus.container-image.group=quarkiverse