quarkus.banner.enabled=false
quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.reuse=false
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%dev.quarkus.camunda.devservices.monitor.enabled=true