quarkus.banner.enabled=false
quarkus.camunda.health.enabled=true
quarkus.http.test-port=0

%dev.quarkus.camunda.active=false
%dev.quarkus.camunda.devservices.enabled=false

%test.quarkus.camunda.active=true
%test.quarkus.camunda.devservices.enabled=true

quarkus.test.integration-test-profile=test